"""initial_schema_with_composite_keys

Revision ID: 36f6c66a9a9a
Revises: 
Create Date: 2025-05-20 20:29:23.091510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36f6c66a9a9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colorants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colorants_id'), 'colorants', ['id'], unique=False)
    op.create_index(op.f('ix_colorants_name'), 'colorants', ['name'], unique=True)
    op.create_table('formulations',
    sa.Column('color_code', sa.String(length=50), nullable=False),
    sa.Column('color_card', sa.String(length=100), nullable=False),
    sa.Column('paint_type', sa.String(length=100), nullable=False),
    sa.Column('base_paint', sa.String(length=100), nullable=False),
    sa.Column('packaging_spec', sa.String(length=100), nullable=False),
    sa.Column('colorant_type', sa.String(length=100), nullable=False),
    sa.Column('color_series', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('color_code', 'color_card', 'paint_type', 'base_paint', 'packaging_spec')
    )
    op.create_index('idx_color_card', 'formulations', ['color_card'], unique=False)
    op.create_index('idx_formulation_search', 'formulations', ['color_code', 'paint_type', 'base_paint'], unique=False)
    op.create_table('colorant_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color_code', sa.String(length=50), nullable=False),
    sa.Column('color_card', sa.String(length=100), nullable=False),
    sa.Column('paint_type', sa.String(length=100), nullable=False),
    sa.Column('base_paint', sa.String(length=100), nullable=False),
    sa.Column('packaging_spec', sa.String(length=100), nullable=False),
    sa.Column('colorant_name', sa.String(length=100), nullable=False),
    sa.Column('weight_g', sa.Numeric(precision=12, scale=7), nullable=True),
    sa.Column('volume_ml', sa.Numeric(precision=12, scale=7), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['color_code', 'color_card', 'paint_type', 'base_paint', 'packaging_spec'], ['formulations.color_code', 'formulations.color_card', 'formulations.paint_type', 'formulations.base_paint', 'formulations.packaging_spec'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_colorant_formulation', 'colorant_details', ['color_code', 'color_card', 'paint_type', 'base_paint', 'packaging_spec'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_colorant_formulation', table_name='colorant_details')
    op.drop_table('colorant_details')
    op.drop_index('idx_formulation_search', table_name='formulations')
    op.drop_index('idx_color_card', table_name='formulations')
    op.drop_table('formulations')
    op.drop_index(op.f('ix_colorants_name'), table_name='colorants')
    op.drop_index(op.f('ix_colorants_id'), table_name='colorants')
    op.drop_table('colorants')
    # ### end Alembic commands ###
